"""
Git Service for pushing generated code to GitHub repositories.
"""
import os
import shutil
import tempfile
import subprocess
from typing import Dict, Any, Optional
from app.core.logger import logger


class GitService:
    """Service for Git operations including cloning, branching, and pushing code."""
    
    def __init__(self):
        self.github_token = os.getenv('GITHUB_TOKEN')
        if not self.github_token:
            logger.warning("GITHUB_TOKEN not set in environment variables")
    
    def push_tests_to_github(
        self,
        repo_url: str,
        tests: Dict[str, Any],
        project_name: str,
        branch_name: str = "savi/tests_generated"
    ) -> Dict[str, Any]:
        """
        Push generated tests to a GitHub repository.
        
        Args:
            repo_url: GitHub repository URL (https://github.com/user/repo.git)
            tests: Generated tests structure with unit_tests, integration_tests, etc.
            project_name: Name of the project for commit message
            branch_name: Branch name to create and push to
            
        Returns:
            Dict with success status and message
        """
        if not self.github_token:
            return {
                "success": False,
                "error": "GITHUB_TOKEN not configured in environment variables"
            }
        
        temp_dir = None
        try:
            # Create temporary directory
            temp_dir = tempfile.mkdtemp(prefix=f"gps_{project_name}_tests_")
            logger.info(f"Created temp directory for tests: {temp_dir}")
            
            # Inject token into repo URL for authentication
            auth_repo_url = self._inject_token_in_url(repo_url)
            
            # Clone repository
            logger.info(f"Cloning repository: {repo_url}")
            self._run_git_command(['git', 'clone', auth_repo_url, temp_dir])
            
            # Configure git user (required for commits)
            self._run_git_command(['git', 'config', 'user.email', 'gps-bot@example.com'], cwd=temp_dir)
            self._run_git_command(['git', 'config', 'user.name', 'GPS Bot'], cwd=temp_dir)
            
            # Create and checkout new branch
            logger.info(f"Creating branch: {branch_name}")
            self._run_git_command(['git', 'checkout', '-b', branch_name], cwd=temp_dir)
            
            # Write generated test files to disk
            self._write_tests_to_disk(temp_dir, tests)
            
            # Git add all files
            logger.info("Adding test files to git")
            self._run_git_command(['git', 'add', '.'], cwd=temp_dir)
            
            # Check if there are changes to commit
            status_result = self._run_git_command(
                ['git', 'status', '--porcelain'], 
                cwd=temp_dir,
                capture_output=True
            )
            
            if not status_result.stdout.strip():
                logger.info("No test changes to commit")
                return {
                    "success": True,
                    "message": "No test changes to commit - tests already up to date"
                }
            
            # Commit changes
            commit_message = f"Add generated tests for {project_name}\n\nGenerated by GPS (Golden Path Studio)"
            logger.info(f"Committing test changes: {commit_message}")
            self._run_git_command(['git', 'commit', '-m', commit_message], cwd=temp_dir)
            
            # Push to remote
            logger.info(f"Pushing tests to remote branch: {branch_name}")
            self._run_git_command(['git', 'push', '-u', 'origin', branch_name], cwd=temp_dir)
            
            logger.info(f"Successfully pushed tests to {repo_url} on branch {branch_name}")
            return {
                "success": True,
                "message": f"Tests successfully pushed to branch '{branch_name}'",
                "branch": branch_name,
                "repo_url": repo_url
            }
            
        except subprocess.CalledProcessError as e:
            error_msg = f"Git command failed: {e.stderr.decode() if e.stderr else str(e)}"
            logger.error(error_msg)
            return {
                "success": False,
                "error": error_msg
            }
        except Exception as e:
            error_msg = f"Failed to push tests to GitHub: {str(e)}"
            logger.error(error_msg)
            return {
                "success": False,
                "error": error_msg
            }
        finally:
            # Cleanup temporary directory
            if temp_dir and os.path.exists(temp_dir):
                try:
                    shutil.rmtree(temp_dir)
                    logger.info(f"Cleaned up temp directory: {temp_dir}")
                except Exception as e:
                    logger.warning(f"Failed to cleanup temp directory: {e}")
    
    def push_code_to_github(
        self,
        repo_url: str,
        code_implementation: Dict[str, Any],
        project_name: str,
        branch_name: str = "savi/code_scaffolded"
    ) -> Dict[str, Any]:
        """
        Push generated code to a GitHub repository.
        
        Args:
            repo_url: GitHub repository URL (https://github.com/user/repo.git)
            code_implementation: Generated code structure with files, docs, config
            project_name: Name of the project for commit message
            branch_name: Branch name to create and push to
            
        Returns:
            Dict with success status and message
        """
        if not self.github_token:
            return {
                "success": False,
                "error": "GITHUB_TOKEN not configured in environment variables"
            }
        
        temp_dir = None
        try:
            # Create temporary directory
            temp_dir = tempfile.mkdtemp(prefix=f"gps_{project_name}_")
            logger.info(f"Created temp directory: {temp_dir}")
            
            # Inject token into repo URL for authentication
            auth_repo_url = self._inject_token_in_url(repo_url)
            
            # Clone repository
            logger.info(f"Cloning repository: {repo_url}")
            self._run_git_command(['git', 'clone', auth_repo_url, temp_dir])
            
            # Configure git user (required for commits)
            self._run_git_command(['git', 'config', 'user.email', 'gps-bot@example.com'], cwd=temp_dir)
            self._run_git_command(['git', 'config', 'user.name', 'GPS Bot'], cwd=temp_dir)
            
            # Create and checkout new branch
            logger.info(f"Creating branch: {branch_name}")
            self._run_git_command(['git', 'checkout', '-b', branch_name], cwd=temp_dir)
            
            # Write generated files to disk
            self._write_code_to_disk(temp_dir, code_implementation)
            
            # Git add all files
            logger.info("Adding files to git")
            self._run_git_command(['git', 'add', '.'], cwd=temp_dir)
            
            # Check if there are changes to commit
            status_result = self._run_git_command(
                ['git', 'status', '--porcelain'], 
                cwd=temp_dir,
                capture_output=True
            )
            
            if not status_result.stdout.strip():
                logger.info("No changes to commit")
                return {
                    "success": True,
                    "message": "No changes to commit - code already up to date"
                }
            
            # Commit changes
            commit_message = f"Add scaffolded code for {project_name}\n\nGenerated by GPS (Golden Path Studio)"
            logger.info(f"Committing changes: {commit_message}")
            self._run_git_command(['git', 'commit', '-m', commit_message], cwd=temp_dir)
            
            # Push to remote
            logger.info(f"Pushing to remote branch: {branch_name}")
            self._run_git_command(['git', 'push', '-u', 'origin', branch_name], cwd=temp_dir)
            
            logger.info(f"Successfully pushed code to {repo_url} on branch {branch_name}")
            return {
                "success": True,
                "message": f"Code successfully pushed to branch '{branch_name}'",
                "branch": branch_name,
                "repo_url": repo_url
            }
            
        except subprocess.CalledProcessError as e:
            error_msg = f"Git command failed: {e.stderr.decode() if e.stderr else str(e)}"
            logger.error(error_msg)
            return {
                "success": False,
                "error": error_msg
            }
        except Exception as e:
            error_msg = f"Failed to push code to GitHub: {str(e)}"
            logger.error(error_msg)
            return {
                "success": False,
                "error": error_msg
            }
        finally:
            # Cleanup temporary directory
            if temp_dir and os.path.exists(temp_dir):
                try:
                    shutil.rmtree(temp_dir)
                    logger.info(f"Cleaned up temp directory: {temp_dir}")
                except Exception as e:
                    logger.warning(f"Failed to cleanup temp directory: {e}")
    
    def _inject_token_in_url(self, repo_url: str) -> str:
        """
        Inject GitHub token into repository URL for authentication.
        
        Converts: https://github.com/user/repo.git
        To: https://TOKEN@github.com/user/repo.git
        """
        if repo_url.startswith('https://github.com/'):
            return repo_url.replace('https://github.com/', f'https://{self.github_token}@github.com/')
        elif repo_url.startswith('https://'):
            # Generic HTTPS URL
            return repo_url.replace('https://', f'https://{self.github_token}@')
        else:
            # Return as-is for SSH URLs or other formats
            return repo_url
    
    def _run_git_command(
        self, 
        command: list, 
        cwd: Optional[str] = None,
        capture_output: bool = False
    ) -> subprocess.CompletedProcess:
        """
        Run a git command and handle errors.
        
        Args:
            command: Git command as list of strings
            cwd: Working directory for the command
            capture_output: Whether to capture stdout/stderr
            
        Returns:
            CompletedProcess object
            
        Raises:
            subprocess.CalledProcessError: If command fails
        """
        logger.debug(f"Running git command: {' '.join(command)}")
        
        result = subprocess.run(
            command,
            cwd=cwd,
            capture_output=True,
            text=True,
            check=True
        )
        
        if capture_output:
            return result
        
        if result.stdout:
            logger.debug(f"Git output: {result.stdout}")
        
        return result
    
    def _write_tests_to_disk(self, base_dir: str, tests: Dict[str, Any]) -> None:
        """
        Write generated test files to disk.
        
        Args:
            base_dir: Base directory to write files to
            tests: Tests structure with unit_tests, integration_tests, test_data, test_configuration
        """
        # Write unit tests
        if tests.get('unit_tests'):
            for test_file in tests['unit_tests']:
                file_path = os.path.join(base_dir, test_file['path'])
                self._write_file(file_path, test_file['content'])
        
        # Write integration tests
        if tests.get('integration_tests'):
            for test_file in tests['integration_tests']:
                file_path = os.path.join(base_dir, test_file['path'])
                self._write_file(file_path, test_file['content'])
        
        # Write test data/fixtures
        if tests.get('test_data'):
            if tests['test_data'].get('fixtures'):
                for fixture in tests['test_data']['fixtures']:
                    file_path = os.path.join(base_dir, fixture['path'])
                    self._write_file(file_path, fixture['content'])
            
            if tests['test_data'].get('factories'):
                for factory in tests['test_data']['factories']:
                    file_path = os.path.join(base_dir, factory['path'])
                    self._write_file(file_path, factory['content'])
        
        # Write test configuration
        if tests.get('test_configuration'):
            for config_file in tests['test_configuration']:
                file_path = os.path.join(base_dir, config_file['path'])
                self._write_file(file_path, config_file['content'])
        
        # Write README for tests if available
        if tests.get('readme'):
            readme_path = os.path.join(base_dir, 'TESTS_README.md')
            self._write_file(readme_path, tests['readme'])
        
        logger.info(f"Wrote all test files to {base_dir}")
    
    def _write_code_to_disk(self, base_dir: str, code_implementation: Dict[str, Any]) -> None:
        """
        Write generated code files to disk.
        
        Args:
            base_dir: Base directory to write files to
            code_implementation: Code structure with files, docs, config
        """
        # Write code files
        if code_implementation.get('files'):
            for file_info in code_implementation['files']:
                file_path = os.path.join(base_dir, file_info['path'])
                self._write_file(file_path, file_info['content'])
        
        # Write documentation files
        if code_implementation.get('documentation'):
            for doc_name, content in code_implementation['documentation'].items():
                file_path = os.path.join(base_dir, doc_name)
                self._write_file(file_path, str(content))
        
        # Write configuration files
        if code_implementation.get('configuration'):
            for config_name, content in code_implementation['configuration'].items():
                file_path = os.path.join(base_dir, config_name)
                self._write_file(file_path, str(content))
        
        logger.info(f"Wrote all files to {base_dir}")
    
    def _write_file(self, file_path: str, content: str) -> None:
        """
        Write a single file to disk, creating directories as needed.
        
        Args:
            file_path: Full path to the file
            content: File content
        """
        # Create parent directories if they don't exist
        os.makedirs(os.path.dirname(file_path), exist_ok=True)
        
        # Write file
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(content)
        
        logger.debug(f"Wrote file: {file_path}")


# Singleton instance
_git_service = None

def get_git_service() -> GitService:
    """Get or create GitService singleton instance."""
    global _git_service
    if _git_service is None:
        _git_service = GitService()
    return _git_service
